#

CC      = gcc -m32
CFLAGS  = -DLINUX 
LDFLAGS = -lpthread -lX11 -ldl -lrt -lm


aos.linux:	clean oberon.o Threads.linux.o
	$(CC) -s -o aos.linux oberon.o Threads.linux.o $(LDFLAGS)

oberon.o:	oberon.c
	$(CC) -c $(CFLAGS) oberon.c

Threads.linux.o:	Threads.h Threads.linux.c
	$(CC) -c $(CFLAGS) Threads.linux.c 

clean:
	rm -f *.o 

distclean:
	rm -f *.o aos.linux*

