#

CC=gcc 
CFLAGS  = -DSOLARIS -threads
LDFLAGS = -lthread -L/usr/openwin/lib -lX11 -ldl -lrt -lm



aos.solaris:	clean oberon.o Threads.solaris.o
	$(CC) -s -o aos.solaris oberon.o Threads.solaris.o $(LDFLAGS)

oberon.o:	oberon.c
	$(CC) -c $(CFLAGS) oberon.c

Threads.solaris.o:	Threads.h Threads.solaris.c
	$(CC) -c $(CFLAGS) Threads.solaris.c 

clean:
	rm -f *.o 

distclean:
	rm -f *.o aos.solaris*

