#

CC      = gcc 
CFLAGS  = -m32 -DMAC -I/usr/X11R6/include
LDFLAGS = -lpthread -L/usr/X11R6/lib -lX11 -lXext -lm



aos.darwin:	clean oberon.o Threads.darwin.o 
	$(CC) -s -o aos.darwin oberon.o Threads.darwin.o  $(LDFLAGS) \
		-arch i386 -framework CoreServices

oberon.o:	oberon.c
	$(CC) -c $(CFLAGS) oberon.c

Threads.darwin.o:	Threads.h Threads.darwin.c
	$(CC) -c $(CFLAGS) Threads.darwin.c 

clean:
	rm -f *.o 

distclean:
	rm -f *.o aos.darwin*

